import os
from jinja2 import Environment, FileSystemLoader


KERNEL_PATH="./"

# Set up Jinja environment
env = Environment(loader=FileSystemLoader(KERNEL_PATH))

# Parameter list
operations = [
    {"id": 1, 
     "block_size": 256, 
     "M": 32, 
     "N": 128, 
     "K": 256, 
     "MXdl": 32, 
     "NXdl": 32, 
     "MPerXdl": 1, 
     "NPerXdl": 1, 
     "ABlockTransferThreadClusterLengths": "16, 16, 1", 
     "BBlockTransferThreadClusterLengths": "16, 16, 1", 
    "CBlockTransferClusterLengths": "1, 16, 1, 16", 
    "CBlockTransferScalarPerVector": "8, 8, 1", 
    "CShuffle_MX_Per_Wave_Pershuffle": 1,
    "CShuffle_NX_Per_Wave_Pershuffle": 1,
    "BlockGemmPipelineScheduler": "ck::BlockGemmPipelineScheduler::Intrawave",
    "BlockGemmPipelineVersion": "ck::BlockGemmPipelineVersion::v2", 
    "GemmSpecialization": "ck::tensor_operation::device::GemmSpecialization::MNKPadding",    
    "ABlockTransferSrcScalarPerVector": 16, 
    "BBlockTransferSrcScalarPerVector": 16
    },
    {"id": 2, 
     "block_size": 256, 
     "M": 32, "N": 128, "K": 512, 
     "MXdl": 32, "NXdl": 32, 
     "MPerXdl": 1, "NPerXdl": 1, 
    "ABlockTransferThreadClusterLengths": "32, 8, 1", 
    "BBlockTransferThreadClusterLengths": "32, 8, 1", 
    "CBlockTransferClusterLengths": "1, 16, 1, 16", 
    "CBlockTransferScalarPerVector": "8, 8, 1", 
    "CShuffle_MX_Per_Wave_Pershuffle": 1,
    "CShuffle_NX_Per_Wave_Pershuffle": 1,
    "BlockGemmPipelineScheduler": "ck::BlockGemmPipelineScheduler::Intrawave",
    "BlockGemmPipelineVersion": "ck::BlockGemmPipelineVersion::v2", 
    "GemmSpecialization": "ck::tensor_operation::device::GemmSpecialization::MNKPadding",
    "ABlockTransferSrcScalarPerVector": 16, 
    "BBlockTransferSrcScalarPerVector": 16
    },
    {"id": 3, 
     "block_size": 256, 
     "M": 256, "N": 128, "K": 128, 
     "MXdl": 32, "NXdl": 32, 
     "MPerXdl": 8, "NPerXdl": 1, 
    "ABlockTransferThreadClusterLengths": "8, 32, 1", 
    "BBlockTransferThreadClusterLengths": "8, 32, 1", 
    "CBlockTransferClusterLengths": "1, 32, 1, 8", 
    "CBlockTransferScalarPerVector": "8, 8, 1", 
    "CShuffle_MX_Per_Wave_Pershuffle": 1,
    "CShuffle_NX_Per_Wave_Pershuffle": 1,
    "BlockGemmPipelineScheduler": "ck::BlockGemmPipelineScheduler::Intrawave",
    "BlockGemmPipelineVersion": "ck::BlockGemmPipelineVersion::v2", 
    "GemmSpecialization": "ck::tensor_operation::device::GemmSpecialization::MNKPadding",
    "ABlockTransferSrcScalarPerVector": 16, 
    "BBlockTransferSrcScalarPerVector": 16
    },
    {"id": 4, 
     "block_size": 256, 
     "M": 128, "N": 128, "K": 128, 
     "MXdl": 32, "NXdl": 32, 
     "MPerXdl": 4, "NPerXdl": 1, 
    "ABlockTransferThreadClusterLengths": "8, 32, 1", 
    "BBlockTransferThreadClusterLengths": "8, 32, 1", 
    "CBlockTransferClusterLengths": "1, 32, 1, 8", 
    "CBlockTransferScalarPerVector": "8, 8, 1",
    "CShuffle_MX_Per_Wave_Pershuffle": 1,
    "CShuffle_NX_Per_Wave_Pershuffle": 1,
    "BlockGemmPipelineScheduler": "ck::BlockGemmPipelineScheduler::Intrawave",
    "BlockGemmPipelineVersion": "ck::BlockGemmPipelineVersion::v2", 
    "GemmSpecialization": "ck::tensor_operation::device::GemmSpecialization::MNKPadding",
    "ABlockTransferSrcScalarPerVector": 16, 
    "BBlockTransferSrcScalarPerVector": 16
    },
    {"id": 5, 
     "block_size": 256, 
     "M": 64, "N": 128, "K": 128, 
     "MXdl": 32, "NXdl": 32, 
     "MPerXdl": 2, "NPerXdl": 1, 
    "ABlockTransferThreadClusterLengths": "8, 32, 1", 
    "BBlockTransferThreadClusterLengths": "8, 32, 1", 
    "CBlockTransferClusterLengths": "1, 32, 1, 8", 
    "CBlockTransferScalarPerVector": "8, 8, 1",
    "CShuffle_MX_Per_Wave_Pershuffle": 1,
    "CShuffle_NX_Per_Wave_Pershuffle": 1,
    "BlockGemmPipelineScheduler": "ck::BlockGemmPipelineScheduler::Intrawave",
    "BlockGemmPipelineVersion": "ck::BlockGemmPipelineVersion::v2", 
    "GemmSpecialization": "ck::tensor_operation::device::GemmSpecialization::MNKPadding",
    "ABlockTransferSrcScalarPerVector": 16, 
    "BBlockTransferSrcScalarPerVector": 16
    },
    {"id": 6, 
     "block_size": 256, 
     "M": 32, "N": 128, "K": 128, 
     "MXdl": 32, "NXdl": 32, 
     "MPerXdl": 1, "NPerXdl": 1, 
    "ABlockTransferThreadClusterLengths": "8, 32, 1", 
    "BBlockTransferThreadClusterLengths": "8, 32, 1", 
    "CBlockTransferClusterLengths": "1, 32, 1, 8", 
    "CBlockTransferScalarPerVector": "8, 8, 1",
    "CShuffle_MX_Per_Wave_Pershuffle": 1,
    "CShuffle_NX_Per_Wave_Pershuffle": 1,
    "BlockGemmPipelineScheduler": "ck::BlockGemmPipelineScheduler::Intrawave",
    "BlockGemmPipelineVersion": "ck::BlockGemmPipelineVersion::v2", 
    "GemmSpecialization": "ck::tensor_operation::device::GemmSpecialization::MNKPadding",
    "ABlockTransferSrcScalarPerVector": 16, 
    "BBlockTransferSrcScalarPerVector": 16
    },
    {"id": 7, 
     "block_size": 256, 
     "M": 256, "N": 256, "K": 128, 
     "MXdl": 32, "NXdl": 32, 
     "MPerXdl": 8, "NPerXdl": 2, 
    "ABlockTransferThreadClusterLengths": "8, 32, 1", 
    "BBlockTransferThreadClusterLengths": "8, 32, 1", 
    "CBlockTransferClusterLengths": "1, 32, 1, 8", 
    "CBlockTransferScalarPerVector": "8, 8, 1",
    "CShuffle_MX_Per_Wave_Pershuffle": 1,
    "CShuffle_NX_Per_Wave_Pershuffle": 1,
    "BlockGemmPipelineScheduler": "ck::BlockGemmPipelineScheduler::Intrawave",
    "BlockGemmPipelineVersion": "ck::BlockGemmPipelineVersion::v2", 
    "GemmSpecialization": "ck::tensor_operation::device::GemmSpecialization::MNKPadding",
    "ABlockTransferSrcScalarPerVector": 16, 
    "BBlockTransferSrcScalarPerVector": 16
    },
    {"id": 8, 
     "block_size": 256, 
     "M": 128, "N": 256, "K": 128, 
     "MXdl": 32, "NXdl": 32, 
     "MPerXdl": 4, "NPerXdl": 2, 
    "ABlockTransferThreadClusterLengths": "8, 32, 1", 
    "BBlockTransferThreadClusterLengths": "8, 32, 1", 
    "CBlockTransferClusterLengths": "1, 32, 1, 8", 
    "CBlockTransferScalarPerVector": "8, 8, 1",
    "CShuffle_MX_Per_Wave_Pershuffle": 1,
    "CShuffle_NX_Per_Wave_Pershuffle": 1,
    "BlockGemmPipelineScheduler": "ck::BlockGemmPipelineScheduler::Intrawave",
    "BlockGemmPipelineVersion": "ck::BlockGemmPipelineVersion::v2", 
    "GemmSpecialization": "ck::tensor_operation::device::GemmSpecialization::MNKPadding",
    "ABlockTransferSrcScalarPerVector": 16, 
    "BBlockTransferSrcScalarPerVector": 16
    },
    {"id": 9, 
     "block_size": 256, 
     "M": 64, "N": 256, "K": 128, 
     "MXdl": 32, "NXdl": 32, 
     "MPerXdl": 2, "NPerXdl": 2, 
    "ABlockTransferThreadClusterLengths": "8, 32, 1", 
    "BBlockTransferThreadClusterLengths": "8, 32, 1", 
    "CBlockTransferClusterLengths": "1, 32, 1, 8", 
    "CBlockTransferScalarPerVector": "8, 8, 1",
    "CShuffle_MX_Per_Wave_Pershuffle": 1,
    "CShuffle_NX_Per_Wave_Pershuffle": 1,
    "BlockGemmPipelineScheduler": "ck::BlockGemmPipelineScheduler::Intrawave",
    "BlockGemmPipelineVersion": "ck::BlockGemmPipelineVersion::v2", 
    "GemmSpecialization": "ck::tensor_operation::device::GemmSpecialization::MNKPadding",
    "ABlockTransferSrcScalarPerVector": 16, 
    "BBlockTransferSrcScalarPerVector": 16
    },
    {"id": 10, 
     "block_size": 256, 
     "M": 32, "N": 256, "K": 128, 
     "MXdl": 32, "NXdl": 32, 
     "MPerXdl": 1, "NPerXdl": 2, 
    "ABlockTransferThreadClusterLengths": "8, 32, 1", 
    "BBlockTransferThreadClusterLengths": "8, 32, 1", 
    "CBlockTransferClusterLengths": "1, 32, 1, 8", 
    "CBlockTransferScalarPerVector": "8, 8, 1",
    "CShuffle_MX_Per_Wave_Pershuffle": 1,
    "CShuffle_NX_Per_Wave_Pershuffle": 1,
    "BlockGemmPipelineScheduler": "ck::BlockGemmPipelineScheduler::Intrawave",
    "BlockGemmPipelineVersion": "ck::BlockGemmPipelineVersion::v2", 
    "GemmSpecialization": "ck::tensor_operation::device::GemmSpecialization::MNKPadding",
    "ABlockTransferSrcScalarPerVector": 16, 
    "BBlockTransferSrcScalarPerVector": 16
    },
    {"id": 11, 
     "block_size": 256, 
     "M": 64, "N": 512, "K": 128, 
     "MXdl": 32, "NXdl": 32, 
     "MPerXdl": 2, "NPerXdl": 4, 
    "ABlockTransferThreadClusterLengths": "8, 32, 1", 
    "BBlockTransferThreadClusterLengths": "8, 32, 1", 
    "CBlockTransferClusterLengths": "1, 32, 1, 8", 
    "CBlockTransferScalarPerVector": "8, 8, 1",
    "CShuffle_MX_Per_Wave_Pershuffle": 1,
    "CShuffle_NX_Per_Wave_Pershuffle": 1,
    "BlockGemmPipelineScheduler": "ck::BlockGemmPipelineScheduler::Intrawave",
    "BlockGemmPipelineVersion": "ck::BlockGemmPipelineVersion::v2", 
    "GemmSpecialization": "ck::tensor_operation::device::GemmSpecialization::MNKPadding",
    "ABlockTransferSrcScalarPerVector": 16, 
    "BBlockTransferSrcScalarPerVector": 16
    },
    {"id": 12, 
     "block_size": 256, 
     "M": 32, "N": 512, "K": 128, 
     "MXdl": 32, "NXdl": 32, 
     "MPerXdl": 1, "NPerXdl": 4, 
    "ABlockTransferThreadClusterLengths": "8, 32, 1", 
    "BBlockTransferThreadClusterLengths": "8, 32, 1", 
    "CBlockTransferClusterLengths": "1, 32, 1, 8", 
    "CBlockTransferScalarPerVector": "8, 8, 1",
    "CShuffle_MX_Per_Wave_Pershuffle": 1,
    "CShuffle_NX_Per_Wave_Pershuffle": 1,
    "BlockGemmPipelineScheduler": "ck::BlockGemmPipelineScheduler::Intrawave",
    "BlockGemmPipelineVersion": "ck::BlockGemmPipelineVersion::v2", 
    "GemmSpecialization": "ck::tensor_operation::device::GemmSpecialization::MNKPadding",
    "ABlockTransferSrcScalarPerVector": 16, 
    "BBlockTransferSrcScalarPerVector": 16
    },
    {"id": 13, 
     "block_size": 256, 
     "M": 128, "N": 128, "K": 256, 
     "MXdl": 32, "NXdl": 32, 
     "MPerXdl": 4, "NPerXdl": 1, 
    "ABlockTransferThreadClusterLengths": "16, 16, 1", 
    "BBlockTransferThreadClusterLengths": "16, 16, 1", 
    "CBlockTransferClusterLengths": "1, 32, 1, 8", 
    "CBlockTransferScalarPerVector": "8, 8, 1",
    "CShuffle_MX_Per_Wave_Pershuffle": 1,
    "CShuffle_NX_Per_Wave_Pershuffle": 1,
    "BlockGemmPipelineScheduler": "ck::BlockGemmPipelineScheduler::Intrawave",
    "BlockGemmPipelineVersion": "ck::BlockGemmPipelineVersion::v2", 
    "GemmSpecialization": "ck::tensor_operation::device::GemmSpecialization::MNKPadding",
    "ABlockTransferSrcScalarPerVector": 16, 
    "BBlockTransferSrcScalarPerVector": 16
    },
    {"id": 14, 
     "block_size": 256, 
     "M": 64, "N": 128, "K": 256, 
     "MXdl": 32, "NXdl": 32, 
     "MPerXdl": 2, "NPerXdl": 1, 
    "ABlockTransferThreadClusterLengths": "16, 16, 1", 
    "BBlockTransferThreadClusterLengths": "16, 16, 1", 
    "CBlockTransferClusterLengths": "1, 32, 1, 8", 
    "CBlockTransferScalarPerVector": "8, 8, 1",
    "CShuffle_MX_Per_Wave_Pershuffle": 1,
    "CShuffle_NX_Per_Wave_Pershuffle": 1,
    "BlockGemmPipelineScheduler": "ck::BlockGemmPipelineScheduler::Intrawave",
    "BlockGemmPipelineVersion": "ck::BlockGemmPipelineVersion::v2", 
    "GemmSpecialization": "ck::tensor_operation::device::GemmSpecialization::MNKPadding",
    "ABlockTransferSrcScalarPerVector": 16, 
    "BBlockTransferSrcScalarPerVector": 16
    },
    {"id": 15, 
     "block_size": 256, 
     "M": 32, "N": 128, "K": 256, 
     "MXdl": 32, "NXdl": 32, 
     "MPerXdl": 1, "NPerXdl": 1, 
    "ABlockTransferThreadClusterLengths": "16, 16, 1", 
    "BBlockTransferThreadClusterLengths": "16, 16, 1", 
    "CBlockTransferClusterLengths": "1, 32, 1, 8", 
    "CBlockTransferScalarPerVector": "8, 8, 1",
    "CShuffle_MX_Per_Wave_Pershuffle": 1,
    "CShuffle_NX_Per_Wave_Pershuffle": 1,
    "BlockGemmPipelineScheduler": "ck::BlockGemmPipelineScheduler::Intrawave",
    "BlockGemmPipelineVersion": "ck::BlockGemmPipelineVersion::v2", 
    "GemmSpecialization": "ck::tensor_operation::device::GemmSpecialization::MNKPadding",
    "ABlockTransferSrcScalarPerVector": 16, 
    "BBlockTransferSrcScalarPerVector": 16
    },
    {"id": 16, 
     "block_size": 256, 
     "M": 64, "N": 128, "K": 512, 
     "MXdl": 32, "NXdl": 32, 
     "MPerXdl": 2, "NPerXdl": 1, 
    "ABlockTransferThreadClusterLengths": "32, 8, 1", 
    "BBlockTransferThreadClusterLengths": "32, 8, 1", 
    "CBlockTransferClusterLengths": "1, 32, 1, 8", 
    "CBlockTransferScalarPerVector": "8, 8, 1",
    "CShuffle_MX_Per_Wave_Pershuffle": 1,
    "CShuffle_NX_Per_Wave_Pershuffle": 1,
    "BlockGemmPipelineScheduler": "ck::BlockGemmPipelineScheduler::Intrawave",
    "BlockGemmPipelineVersion": "ck::BlockGemmPipelineVersion::v2", 
    "GemmSpecialization": "ck::tensor_operation::device::GemmSpecialization::MNKPadding",
    "ABlockTransferSrcScalarPerVector": 16, 
    "BBlockTransferSrcScalarPerVector": 16
    },
    {"id": 17, 
     "block_size": 256, 
     "M": 32, "N": 128, "K": 512, 
     "MXdl": 32, "NXdl": 32, 
     "MPerXdl": 1, "NPerXdl": 1, 
    "ABlockTransferThreadClusterLengths": "32, 8, 1", 
    "BBlockTransferThreadClusterLengths": "32, 8, 1", 
    "CBlockTransferClusterLengths": "1, 32, 1, 8", 
    "CBlockTransferScalarPerVector": "8, 8, 1",
    "CShuffle_MX_Per_Wave_Pershuffle": 1,
    "CShuffle_NX_Per_Wave_Pershuffle": 1,
    "BlockGemmPipelineScheduler": "ck::BlockGemmPipelineScheduler::Intrawave",
    "BlockGemmPipelineVersion": "ck::BlockGemmPipelineVersion::v2", 
    "GemmSpecialization": "ck::tensor_operation::device::GemmSpecialization::MNKPadding",
    "ABlockTransferSrcScalarPerVector": 16, 
    "BBlockTransferSrcScalarPerVector": 16
    },
    {"id": 18, 
     "block_size": 256, 
     "M": 128, "N": 256, "K": 256, 
     "MXdl": 32, "NXdl": 32, 
     "MPerXdl": 4, "NPerXdl": 2, 
    "ABlockTransferThreadClusterLengths": "16, 16, 1", 
    "BBlockTransferThreadClusterLengths": "16, 16, 1", 
    "CBlockTransferClusterLengths": "1, 32, 1, 8", 
    "CBlockTransferScalarPerVector": "8, 8, 1",
    "CShuffle_MX_Per_Wave_Pershuffle": 1,
    "CShuffle_NX_Per_Wave_Pershuffle": 1,
    "BlockGemmPipelineScheduler": "ck::BlockGemmPipelineScheduler::Intrawave",
    "BlockGemmPipelineVersion": "ck::BlockGemmPipelineVersion::v2", 
    "GemmSpecialization": "ck::tensor_operation::device::GemmSpecialization::MNKPadding",
    "ABlockTransferSrcScalarPerVector": 16, 
    "BBlockTransferSrcScalarPerVector": 16
    },
    {"id": 19, 
     "block_size": 256, 
     "M": 64, "N": 256, "K": 256, 
     "MXdl": 32, "NXdl": 32, 
     "MPerXdl": 2, "NPerXdl": 2, 
    "ABlockTransferThreadClusterLengths": "16, 16, 1", 
    "BBlockTransferThreadClusterLengths": "16, 16, 1", 
    "CBlockTransferClusterLengths": "1, 32, 1, 8", 
    "CBlockTransferScalarPerVector": "8, 8, 1",
    "CShuffle_MX_Per_Wave_Pershuffle": 1,
    "CShuffle_NX_Per_Wave_Pershuffle": 1,
    "BlockGemmPipelineScheduler": "ck::BlockGemmPipelineScheduler::Intrawave",
    "BlockGemmPipelineVersion": "ck::BlockGemmPipelineVersion::v2", 
    "GemmSpecialization": "ck::tensor_operation::device::GemmSpecialization::MNKPadding",
    "ABlockTransferSrcScalarPerVector": 16, 
    "BBlockTransferSrcScalarPerVector": 16
    },
    {"id": 20, 
     "block_size": 256, 
     "M": 32, "N": 256, "K": 256, 
     "MXdl": 32, "NXdl": 32, 
     "MPerXdl": 1, "NPerXdl": 2, 
    "ABlockTransferThreadClusterLengths": "16, 16, 1", 
    "BBlockTransferThreadClusterLengths": "16, 16, 1", 
    "CBlockTransferClusterLengths": "1, 32, 1, 8", 
    "CBlockTransferScalarPerVector": "8, 8, 1",
    "CShuffle_MX_Per_Wave_Pershuffle": 1,
    "CShuffle_NX_Per_Wave_Pershuffle": 1,
    "BlockGemmPipelineScheduler": "ck::BlockGemmPipelineScheduler::Intrawave",
    "BlockGemmPipelineVersion": "ck::BlockGemmPipelineVersion::v2", 
    "GemmSpecialization": "ck::tensor_operation::device::GemmSpecialization::MNKPadding",
    "ABlockTransferSrcScalarPerVector": 16, 
    "BBlockTransferSrcScalarPerVector": 16
    },
    {"id": 21, 
     "block_size": 256, 
     "M": 64, "N": 256, "K": 512, 
     "MXdl": 32, "NXdl": 32, 
     "MPerXdl": 2, "NPerXdl": 2, 
    "ABlockTransferThreadClusterLengths": "32, 8, 1", 
    "BBlockTransferThreadClusterLengths": "32, 8, 1", 
    "CBlockTransferClusterLengths": "1, 32, 1, 8", 
    "CBlockTransferScalarPerVector": "8, 8, 1",
    "CShuffle_MX_Per_Wave_Pershuffle": 1,
    "CShuffle_NX_Per_Wave_Pershuffle": 1,
    "BlockGemmPipelineScheduler": "ck::BlockGemmPipelineScheduler::Intrawave",
    "BlockGemmPipelineVersion": "ck::BlockGemmPipelineVersion::v2", 
    "GemmSpecialization": "ck::tensor_operation::device::GemmSpecialization::MNKPadding",
    "ABlockTransferSrcScalarPerVector": 16, 
    "BBlockTransferSrcScalarPerVector": 16
    },
    {"id": 22, 
     "block_size": 256, 
     "M": 32, "N": 256, "K": 512, 
     "MXdl": 32, "NXdl": 32, 
     "MPerXdl": 1, "NPerXdl": 2, 
    "ABlockTransferThreadClusterLengths": "32, 8, 1", 
    "BBlockTransferThreadClusterLengths": "32, 8, 1", 
    "CBlockTransferClusterLengths": "1, 32, 1, 8", 
    "CBlockTransferScalarPerVector": "8, 8, 1",
    "CShuffle_MX_Per_Wave_Pershuffle": 1,
    "CShuffle_NX_Per_Wave_Pershuffle": 1,
    "BlockGemmPipelineScheduler": "ck::BlockGemmPipelineScheduler::Intrawave",
    "BlockGemmPipelineVersion": "ck::BlockGemmPipelineVersion::v2", 
    "GemmSpecialization": "ck::tensor_operation::device::GemmSpecialization::MNKPadding",
    "ABlockTransferSrcScalarPerVector": 16, 
    "BBlockTransferSrcScalarPerVector": 16
    },
    {"id": 23, 
     "block_size": 256, 
     "M": 64, "N": 512, "K": 256, 
     "MXdl": 32, "NXdl": 32, 
     "MPerXdl": 2, "NPerXdl": 4, 
    "ABlockTransferThreadClusterLengths": "16, 16, 1", 
    "BBlockTransferThreadClusterLengths": "16, 16, 1", 
    "CBlockTransferClusterLengths": "1, 32, 1, 8", 
    "CBlockTransferScalarPerVector": "8, 8, 1",
    "CShuffle_MX_Per_Wave_Pershuffle": 1,
    "CShuffle_NX_Per_Wave_Pershuffle": 1,
    "BlockGemmPipelineScheduler": "ck::BlockGemmPipelineScheduler::Intrawave",
    "BlockGemmPipelineVersion": "ck::BlockGemmPipelineVersion::v2", 
    "GemmSpecialization": "ck::tensor_operation::device::GemmSpecialization::MNKPadding",
    "ABlockTransferSrcScalarPerVector": 16, 
    "BBlockTransferSrcScalarPerVector": 16
    },
    {"id": 24, 
     "block_size": 256, 
     "M": 32, "N": 512, "K": 256, 
     "MXdl": 32, "NXdl": 32, 
     "MPerXdl": 1, "NPerXdl": 4, 
    "ABlockTransferThreadClusterLengths": "16, 16, 1", 
    "BBlockTransferThreadClusterLengths": "16, 16, 1", 
    "CBlockTransferClusterLengths": "1, 32, 1, 8", 
    "CBlockTransferScalarPerVector": "8, 8, 1",
    "CShuffle_MX_Per_Wave_Pershuffle": 1,
    "CShuffle_NX_Per_Wave_Pershuffle": 1,
    "BlockGemmPipelineScheduler": "ck::BlockGemmPipelineScheduler::Intrawave",
    "BlockGemmPipelineVersion": "ck::BlockGemmPipelineVersion::v2", 
    "GemmSpecialization": "ck::tensor_operation::device::GemmSpecialization::MNKPadding",
    "ABlockTransferSrcScalarPerVector": 16, 
    "BBlockTransferSrcScalarPerVector": 16
    },
    {"id": 25, 
     "block_size": 256, 
     "M": 16, "N": 64, "K": 256, 
     "MXdl": 16, "NXdl": 16, 
     "MPerXdl": 1, "NPerXdl": 1, 
    "ABlockTransferThreadClusterLengths": "16, 16, 1", 
    "BBlockTransferThreadClusterLengths": "16, 16, 1", 
    "CBlockTransferClusterLengths": "1, 16, 1, 16", 
    "CBlockTransferScalarPerVector": "4, 4, 1",
    "CShuffle_MX_Per_Wave_Pershuffle": 1,
    "CShuffle_NX_Per_Wave_Pershuffle": 1,
    "BlockGemmPipelineScheduler": "ck::BlockGemmPipelineScheduler::Intrawave",
    "BlockGemmPipelineVersion": "ck::BlockGemmPipelineVersion::v2", 
    "GemmSpecialization": "ck::tensor_operation::device::GemmSpecialization::MNKPadding",
    "ABlockTransferSrcScalarPerVector": 16, 
    "BBlockTransferSrcScalarPerVector": 16
    },
    {"id": 26, 
     "block_size": 256, 
     "M": 16, "N": 128, "K": 256, 
     "MXdl": 16, "NXdl": 16, 
     "MPerXdl": 1, "NPerXdl": 2, 
    "ABlockTransferThreadClusterLengths": "16, 16, 1", 
    "BBlockTransferThreadClusterLengths": "16, 16, 1", 
    "CBlockTransferClusterLengths": "1, 16, 1, 16", 
    "CBlockTransferScalarPerVector": "4, 4, 1",
    "CShuffle_MX_Per_Wave_Pershuffle": 1,
    "CShuffle_NX_Per_Wave_Pershuffle": 1,
    "BlockGemmPipelineScheduler": "ck::BlockGemmPipelineScheduler::Intrawave",
    "BlockGemmPipelineVersion": "ck::BlockGemmPipelineVersion::v2", 
    "GemmSpecialization": "ck::tensor_operation::device::GemmSpecialization::MNKPadding",
    "ABlockTransferSrcScalarPerVector": 16, 
    "BBlockTransferSrcScalarPerVector": 16
    },
    {"id": 27, 
     "block_size": 256, 
     "M": 16, "N": 256, "K": 256, 
     "MXdl": 16, "NXdl": 16, 
     "MPerXdl": 1, "NPerXdl": 4, 
    "ABlockTransferThreadClusterLengths": "16, 16, 1", 
    "BBlockTransferThreadClusterLengths": "16, 16, 1", 
    "CBlockTransferClusterLengths": "1, 16, 1, 16", 
    "CBlockTransferScalarPerVector": "4, 4, 1",
    "CShuffle_MX_Per_Wave_Pershuffle": 1,
    "CShuffle_NX_Per_Wave_Pershuffle": 1,
    "BlockGemmPipelineScheduler": "ck::BlockGemmPipelineScheduler::Intrawave",
    "BlockGemmPipelineVersion": "ck::BlockGemmPipelineVersion::v2", 
    "GemmSpecialization": "ck::tensor_operation::device::GemmSpecialization::MNKPadding",
    "ABlockTransferSrcScalarPerVector": 16, 
    "BBlockTransferSrcScalarPerVector": 16
    },
    {"id": 28, 
     "block_size": 256, 
     "M": 16, "N": 512, "K": 256, 
     "MXdl": 16, "NXdl": 16, 
     "MPerXdl": 1, "NPerXdl": 8, 
    "ABlockTransferThreadClusterLengths": "16, 16, 1", 
    "BBlockTransferThreadClusterLengths": "16, 16, 1", 
    "CBlockTransferClusterLengths": "1, 16, 1, 16", 
    "CBlockTransferScalarPerVector": "4, 4, 1",
    "CShuffle_MX_Per_Wave_Pershuffle": 1,
    "CShuffle_NX_Per_Wave_Pershuffle": 1,
    "BlockGemmPipelineScheduler": "ck::BlockGemmPipelineScheduler::Intrawave",
    "BlockGemmPipelineVersion": "ck::BlockGemmPipelineVersion::v2", 
    "GemmSpecialization": "ck::tensor_operation::device::GemmSpecialization::MNKPadding",
    "ABlockTransferSrcScalarPerVector": 16, 
    "BBlockTransferSrcScalarPerVector": 16
    },
    {"id": 29, 
     "block_size": 256, 
     "M": 16, "N": 64, "K": 512, 
     "MXdl": 16, "NXdl": 16, 
     "MPerXdl": 1, "NPerXdl": 1, 
    "ABlockTransferThreadClusterLengths": "32, 8, 1", 
    "BBlockTransferThreadClusterLengths": "32, 8, 1", 
    "CBlockTransferClusterLengths": "1, 16, 1, 16", 
    "CBlockTransferScalarPerVector": "4, 4, 1",
    "CShuffle_MX_Per_Wave_Pershuffle": 1,
    "CShuffle_NX_Per_Wave_Pershuffle": 1,
    "BlockGemmPipelineScheduler": "ck::BlockGemmPipelineScheduler::Intrawave",
    "BlockGemmPipelineVersion": "ck::BlockGemmPipelineVersion::v2", 
    "GemmSpecialization": "ck::tensor_operation::device::GemmSpecialization::MNKPadding",
    "ABlockTransferSrcScalarPerVector": 16, 
    "BBlockTransferSrcScalarPerVector": 16
    },
    {"id": 30, 
     "block_size": 256, 
     "M": 16, "N": 128, "K": 512, 
     "MXdl": 16, "NXdl": 16, 
     "MPerXdl": 1, "NPerXdl": 2, 
    "ABlockTransferThreadClusterLengths": "32, 8, 1", 
    "BBlockTransferThreadClusterLengths": "32, 8, 1", 
    "CBlockTransferClusterLengths": "1, 16, 1, 16", 
    "CBlockTransferScalarPerVector": "4, 4, 1",
    "CShuffle_MX_Per_Wave_Pershuffle": 1,
    "CShuffle_NX_Per_Wave_Pershuffle": 1,
    "BlockGemmPipelineScheduler": "ck::BlockGemmPipelineScheduler::Intrawave",
    "BlockGemmPipelineVersion": "ck::BlockGemmPipelineVersion::v2", 
    "GemmSpecialization": "ck::tensor_operation::device::GemmSpecialization::MNKPadding",
    "ABlockTransferSrcScalarPerVector": 16, 
    "BBlockTransferSrcScalarPerVector": 16
    },
    {"id": 31, 
     "block_size": 256, 
     "M": 16, "N": 256, "K": 512, 
     "MXdl": 16, "NXdl": 16, 
     "MPerXdl": 1, "NPerXdl": 4, 
    "ABlockTransferThreadClusterLengths": "32, 8, 1", 
    "BBlockTransferThreadClusterLengths": "32, 8, 1", 
    "CBlockTransferClusterLengths": "1, 16, 1, 16", 
    "CBlockTransferScalarPerVector": "4, 4, 1",
    "CShuffle_MX_Per_Wave_Pershuffle": 1,
    "CShuffle_NX_Per_Wave_Pershuffle": 1,
    "BlockGemmPipelineScheduler": "ck::BlockGemmPipelineScheduler::Intrawave",
    "BlockGemmPipelineVersion": "ck::BlockGemmPipelineVersion::v2", 
    "GemmSpecialization": "ck::tensor_operation::device::GemmSpecialization::MNKPadding",
    "ABlockTransferSrcScalarPerVector": 16, 
    "BBlockTransferSrcScalarPerVector": 16
    },
    # # this is a reflect op 29
    # {"id": 32, 
    #  "block_size": 256, 
    #  "M": 16, "N": 64, "K": 512, 
    #  "MXdl": 16, "NXdl": 16, 
    #  "MPerXdl": 1, "NPerXdl": 1, 
    # "ABlockTransferThreadClusterLengths": "32, 8, 1", 
    # "BBlockTransferThreadClusterLengths": "32, 8, 1", 
    # "CBlockTransferClusterLengths": "1, 16, 1, 16", 
    # "CBlockTransferScalarPerVector": "4, 4, 1",
    # "CShuffle_MX_Per_Wave_Pershuffle": 1,
    # "CShuffle_NX_Per_Wave_Pershuffle": 1,
    # "BlockGemmPipelineScheduler": "ck::BlockGemmPipelineScheduler::Intrawave",
    # "BlockGemmPipelineVersion": "ck::BlockGemmPipelineVersion::v2", 
    # "GemmSpecialization": "ck::tensor_operation::device::GemmSpecialization::MNKPadding",
    # "ABlockTransferSrcScalarPerVector": 16, 
    # "BBlockTransferSrcScalarPerVector": 16
    # },
    {"id": 32, 
     "block_size": 256, 
     "M": 16, "N": 64, "K": 256, 
     "MXdl": 16, "NXdl": 16, 
     "MPerXdl": 1, "NPerXdl": 1, 
    "ABlockTransferThreadClusterLengths": "16, 16, 1", 
    "BBlockTransferThreadClusterLengths": "16, 16, 1", 
    "CBlockTransferClusterLengths": "1, 16, 1, 16", 
    "CBlockTransferScalarPerVector": "4, 4, 1",
    "CShuffle_MX_Per_Wave_Pershuffle": 1,
    "CShuffle_NX_Per_Wave_Pershuffle": 1,
    "BlockGemmPipelineScheduler": "ck::BlockGemmPipelineScheduler::Intrawave",
    "BlockGemmPipelineVersion": "ck::BlockGemmPipelineVersion::v1", 
    "GemmSpecialization": "ck::tensor_operation::device::GemmSpecialization::MNKPadding",
    "ABlockTransferSrcScalarPerVector": 16, 
    "BBlockTransferSrcScalarPerVector": 16
    },
    {"id": 33, 
     "block_size": 256, 
     "M": 16, "N": 128, "K": 256, 
     "MXdl": 16, "NXdl": 16, 
     "MPerXdl": 1, "NPerXdl": 2, 
    "ABlockTransferThreadClusterLengths": "16, 16, 1", 
    "BBlockTransferThreadClusterLengths": "16, 16, 1", 
    "CBlockTransferClusterLengths": "1, 16, 1, 16", 
    "CBlockTransferScalarPerVector": "8, 8, 1",
    "CShuffle_MX_Per_Wave_Pershuffle": 1,
    "CShuffle_NX_Per_Wave_Pershuffle": 2,
    "BlockGemmPipelineScheduler": "ck::BlockGemmPipelineScheduler::Intrawave",
    "BlockGemmPipelineVersion": "ck::BlockGemmPipelineVersion::v1", 
    "GemmSpecialization": "ck::tensor_operation::device::GemmSpecialization::MNKPadding",
    "ABlockTransferSrcScalarPerVector": 16, 
    "BBlockTransferSrcScalarPerVector": 16
    },
    {"id": 34, 
     "block_size": 256, 
     "M": 16, "N": 256, "K": 256, 
     "MXdl": 16, "NXdl": 16, 
     "MPerXdl": 1, "NPerXdl": 4, 
    "ABlockTransferThreadClusterLengths": "16, 16, 1", 
    "BBlockTransferThreadClusterLengths": "16, 16, 1", 
    "CBlockTransferClusterLengths": "1, 16, 1, 16", 
    "CBlockTransferScalarPerVector": "8, 8, 1",
    "CShuffle_MX_Per_Wave_Pershuffle": 1,
    "CShuffle_NX_Per_Wave_Pershuffle": 2,
    "BlockGemmPipelineScheduler": "ck::BlockGemmPipelineScheduler::Intrawave",
    "BlockGemmPipelineVersion": "ck::BlockGemmPipelineVersion::v1", 
    "GemmSpecialization": "ck::tensor_operation::device::GemmSpecialization::MNKPadding",
    "ABlockTransferSrcScalarPerVector": 16, 
    "BBlockTransferSrcScalarPerVector": 16
    },
    {"id": 35, 
     "block_size": 256, 
     "M": 16, "N": 512, "K": 256, 
     "MXdl": 16, "NXdl": 16, 
     "MPerXdl": 1, "NPerXdl": 8, 
    "ABlockTransferThreadClusterLengths": "16, 16, 1", 
    "BBlockTransferThreadClusterLengths": "16, 16, 1", 
    "CBlockTransferClusterLengths": "1, 16, 1, 16", 
    "CBlockTransferScalarPerVector": "8, 8, 1",
    "CShuffle_MX_Per_Wave_Pershuffle": 1,
    "CShuffle_NX_Per_Wave_Pershuffle": 2,
    "BlockGemmPipelineScheduler": "ck::BlockGemmPipelineScheduler::Intrawave",
    "BlockGemmPipelineVersion": "ck::BlockGemmPipelineVersion::v1", 
    "GemmSpecialization": "ck::tensor_operation::device::GemmSpecialization::MNKPadding",
    "ABlockTransferSrcScalarPerVector": 16, 
    "BBlockTransferSrcScalarPerVector": 16
    },
    {"id": 36, 
     "block_size": 256, 
     "M": 16, "N": 64, "K": 512, 
     "MXdl": 16, "NXdl": 16, 
     "MPerXdl": 1, "NPerXdl": 1, 
    "ABlockTransferThreadClusterLengths": "32, 8, 1", 
    "BBlockTransferThreadClusterLengths": "32, 8, 1", 
    "CBlockTransferClusterLengths": "1, 16, 1, 16", 
    "CBlockTransferScalarPerVector": "4, 4, 1",
    "CShuffle_MX_Per_Wave_Pershuffle": 1,
    "CShuffle_NX_Per_Wave_Pershuffle": 1,
    "BlockGemmPipelineScheduler": "ck::BlockGemmPipelineScheduler::Intrawave",
    "BlockGemmPipelineVersion": "ck::BlockGemmPipelineVersion::v1", 
    "GemmSpecialization": "ck::tensor_operation::device::GemmSpecialization::MNKPadding",
    "ABlockTransferSrcScalarPerVector": 16, 
    "BBlockTransferSrcScalarPerVector": 16
    },
    {"id": 37, 
     "block_size": 256, 
     "M": 16, "N": 128, "K": 512, 
     "MXdl": 16, "NXdl": 16, 
     "MPerXdl": 1, "NPerXdl": 2, 
    "ABlockTransferThreadClusterLengths": "32, 8, 1", 
    "BBlockTransferThreadClusterLengths": "32, 8, 1", 
    "CBlockTransferClusterLengths": "1, 16, 1, 16", 
    "CBlockTransferScalarPerVector": "8, 8, 1",
    "CShuffle_MX_Per_Wave_Pershuffle": 1,
    "CShuffle_NX_Per_Wave_Pershuffle": 2,
    "BlockGemmPipelineScheduler": "ck::BlockGemmPipelineScheduler::Intrawave",
    "BlockGemmPipelineVersion": "ck::BlockGemmPipelineVersion::v1", 
    "GemmSpecialization": "ck::tensor_operation::device::GemmSpecialization::MNKPadding",
    "ABlockTransferSrcScalarPerVector": 16, 
    "BBlockTransferSrcScalarPerVector": 16
    },
    {"id": 38, 
     "block_size": 256, 
     "M": 16, "N": 256, "K": 512, 
     "MXdl": 16, "NXdl": 16, 
     "MPerXdl": 1, "NPerXdl": 4, 
    "ABlockTransferThreadClusterLengths": "32, 8, 1", 
    "BBlockTransferThreadClusterLengths": "32, 8, 1", 
    "CBlockTransferClusterLengths": "1, 16, 1, 16", 
    "CBlockTransferScalarPerVector": "8, 8, 1",
    "CShuffle_MX_Per_Wave_Pershuffle": 1,
    "CShuffle_NX_Per_Wave_Pershuffle": 2,
    "BlockGemmPipelineScheduler": "ck::BlockGemmPipelineScheduler::Intrawave",
    "BlockGemmPipelineVersion": "ck::BlockGemmPipelineVersion::v1", 
    "GemmSpecialization": "ck::tensor_operation::device::GemmSpecialization::MNKPadding",
    "ABlockTransferSrcScalarPerVector": 16, 
    "BBlockTransferSrcScalarPerVector": 16
    },
    # custom
    # {"id": 39, 
    #  "block_size": 256, 
    #  "M": 16, "N": 256, "K": 128, 
    #  "MXdl": 16, "NXdl": 16, 
    #  "MPerXdl": 1, "NPerXdl": 1, 
    # "ABlockTransferThreadClusterLengths": "16, 16, 1", 
    # "BBlockTransferThreadClusterLengths": "16, 16, 1", 
    # "CBlockTransferClusterLengths": "1, 16, 1, 16", 
    # "CBlockTransferScalarPerVector": "4, 4, 1",
    # "CShuffle_MX_Per_Wave_Pershuffle": 1,
    # "CShuffle_NX_Per_Wave_Pershuffle": 1,
    # "BlockGemmPipelineScheduler": "ck::BlockGemmPipelineScheduler::Intrawave",
    # "BlockGemmPipelineVersion": "ck::BlockGemmPipelineVersion::v1", 
    # "GemmSpecialization": "ck::tensor_operation::device::GemmSpecialization::MNKPadding",
    # "ABlockTransferSrcScalarPerVector": 16, 
    # "BBlockTransferSrcScalarPerVector": 16
    # },
    # Add more operations as needed
]

def generate_kernel_param_files():


    for id, op in enumerate(operations):
        template = env.get_template('machete_mm_kernel.cpp.jinja')

        # Render the template with the operations
        output = template.render(op=op)
        # Write the output to a C++ file
        with open(f'machete_mm_out_{op["id"]}.cpp', 'w') as f:
            f.write(output)

def generate_kernel_header_file():
    # Render the header file
    header_template = env.get_template('machete_mm_kernel.h.jinja')
    header_output = header_template.render(operations=operations)

    # Write the header file
    with open('machete_mm_kernel.h', 'w') as f:
        f.write(header_output)


def generate_launcher_file():
    # Render the header file
    launcher_template = env.get_template('machete_mm_kernel_launcher.cpp.jinja')
    launcher_output = launcher_template.render(operations=operations)

    # Write the header file
    with open('machete_mm_kernel_launcher.cpp', 'w') as f:
        f.write(launcher_output)


if __name__ == "__main__":
    generate_kernel_param_files()
    generate_kernel_header_file()
    generate_launcher_file()